---@class todo-nvim.Config
---@field todo_file string The path to the file to modify
---@field todo_title string The title used for the header at the top of the Markdown file.
---@alias border string
---| '"rounded"' # Like 'single' but with rounded corners
---| '"single"' # Single line box
---| '"double"' # Double line box
---| '"solid"' # Adds padding by a single whitespace cell
---| '"none"' # No border
---| '"shadow"' # Drop shadow effect with background

---@class todo-nvim.TodoItem
---@field desc string description of the TODO action
---@field completed boolean the completion state of the item
