---@class todo-nvim.Config
---@field todo_file string the path to the file to modify
---@alias border string
---| '"rounded"' # Like 'single' but with rounded corners
---| '"single"' # Single line box
---| '"double"' # Double line box
---| '"solid"' # Adds padding by a single whitespace cell
---| '"none"' # No border
---| '"shadow"' # Drop shadow effect with background
---
---TODO:
---@field remove_completed boolean whether to remove TODOs upon completion
---@field save_on_exit boolean whether to autosave on TODO menu closure

---@class todo-nvim.TodoItem
---@field desc string description of the TODO action
---@field completed boolean the completion state of the item
